# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/brightro99"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "instagram"
    name       = "instagram"
    url        = "https://www.instagram.com/brightro99/"

    [social.params]
        icon = "brand-instagram"
